# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9887f4f1a6253c1ab87dc6993ab4b75d33349276aeb95a25d62837c1822d7793d973c4cda4b14899adac723b36c4c99ec7d7a90faa4a72abcc32a2423361a04d

test:
  secret_key_base: 9773596ee83340c60ccff7b29e0b427ac0a17249a359696922cd1cf63dd28cee1ae6b85cb61991b2c5fd085339106b0f4be0944e148cc86bb73b41f7c6dcd0b7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
